//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTER
    {
        public int ID { get; set; }
        public int ID_USER { get; set; }
        public System.DateTime DLOGIN { get; set; }
        public bool CONNECT { get; set; }
    }
}
