//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_REGISTER
    {
        public int ID_USER { get; set; }
        public int ID_REGISTER { get; set; }
        public int COUNT { get; set; }
    }
}
