'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USERS
    Public Property ID As Integer
    Public Property NAME As String
    Public Property EMAIL As String
    Public Property PASSEWORD As String
    Public Property BIRTHDAY As Nullable(Of Date)
    Public Property COUNTRY As String

End Class
